import 'package:logging/logging.dart';
import 'package:saber/data/models/patient.dart';
import 'package:saber/data/supabase/supabase_client.dart';

/// Service for managing patient data in Supabase
class SupabasePatientService {
  static final log = Logger('SupabasePatientService');

  /// Get all patients for the current doctor
  static Future<List<Patient>> getAllPatients() async {
    try {
      log.info('Fetching all patients');

      final response = await supabase
          .from('patients')
          .select()
          .order('created_at', ascending: false);

      final patients = (response as List)
          .map((json) => Patient.fromJson(json as Map<String, dynamic>))
          .toList();

      log.info('Fetched ${patients.length} patients');
      return patients;
    } catch (e) {
      log.severe('Failed to fetch patients', e);
      rethrow;
    }
  }

  /// Get active patients only
  /// Note: 'is_active' column does not exist in current schema, so this returns all patients.
  static Future<List<Patient>> getActivePatients() async {
    try {
      log.info('Fetching active patients (all)');

      final response = await supabase
          .from('patients')
          .select()
          // .eq('is_active', true) // Column does not exist
          .order('created_at', ascending: false);

      final patients = (response as List)
          .map((json) => Patient.fromJson(json as Map<String, dynamic>))
          .toList();

      log.info('Fetched ${patients.length} active patients');
      return patients;
    } catch (e) {
      log.severe('Failed to fetch active patients', e);
      rethrow;
    }
  }

  /// Get patients in waiting queue
  /// Note: 'status' column does not exist, so this returns all patients for now.
  static Future<List<Patient>> getWaitingPatients() async {
    try {
      log.info('Fetching waiting patients (all)');

      final response = await supabase
          .from('patients')
          .select()
          // .eq('status', 'waiting') // Column does not exist
          .order('created_at', ascending: true); // FIFO order

      final patients = (response as List)
          .map((json) => Patient.fromJson(json as Map<String, dynamic>))
          .toList();

      log.info('Fetched ${patients.length} waiting patients');
      return patients;
    } catch (e) {
      log.severe('Failed to fetch waiting patients', e);
      rethrow;
    }
  }

  /// Get a single patient by ID
  static Future<Patient?> getPatient(String patientId) async {
    try {
      log.info('Fetching patient: $patientId');

      final response = await supabase
          .from('patients')
          .select()
          .eq('id', patientId)
          .maybeSingle();

      if (response == null) {
        log.info('Patient not found: $patientId');
        return null;
      }

      final patient = Patient.fromJson(response as Map<String, dynamic>);
      log.info('Fetched patient: ${patient.fullName}');
      return patient;
    } catch (e) {
      log.severe('Failed to fetch patient: $patientId', e);
      rethrow;
    }
  }

  /// Search patients by name
  static Future<List<Patient>> searchPatients(String query) async {
    try {
      log.info('Searching patients with query: $query');

      final response = await supabase
          .from('patients')
          .select()
          .ilike('full_name', '%$query%')
          .order('created_at', ascending: false);

      final patients = (response as List)
          .map((json) => Patient.fromJson(json as Map<String, dynamic>))
          .toList();

      log.info('Found ${patients.length} patients matching "$query"');
      return patients;
    } catch (e) {
      log.severe('Failed to search patients', e);
      rethrow;
    }
  }

  /// Create a new patient
  static Future<Patient> createPatient({
    required String fullName,
    int? age,
    String? gender,
    String? phoneNumber,
    String? email,
    Map<String, dynamic>? medicalHistory,
  }) async {
    try {
      log.info('Creating patient: $fullName');

      final currentUserId = supabase.auth.currentUser?.id;
      if (currentUserId == null) {
        throw Exception('User not authenticated');
      }

      final patient = Patient(
        id: '', // Will be generated by DB
        createdAt: DateTime.now(),
        fullName: fullName,
        age: age,
        gender: gender,
        status: PatientStatus.waiting,
        lastVisit: null,
        doctorId: currentUserId,
        phoneNumber: phoneNumber,
        email: email,
        medicalHistory: medicalHistory,
        isActive: true,
      );

      final response = await supabase
          .from('patients')
          .insert(patient.toInsertJson())
          .select()
          .single();

      final createdPatient = Patient.fromJson(response as Map<String, dynamic>);
      log.info('Created patient: ${createdPatient.id}');
      return createdPatient;
    } catch (e) {
      log.severe('Failed to create patient', e);
      rethrow;
    }
  }

  /// Update patient information
  static Future<Patient> updatePatient(
    String patientId,
    Map<String, dynamic> updates,
  ) async {
    try {
      log.info('Updating patient: $patientId');

      final response = await supabase
          .from('patients')
          .update(updates)
          .eq('id', patientId)
          .select()
          .single();

      final updatedPatient = Patient.fromJson(response as Map<String, dynamic>);
      log.info('Updated patient: ${updatedPatient.id}');
      return updatedPatient;
    } catch (e) {
      log.severe('Failed to update patient: $patientId', e);
      rethrow;
    }
  }

  /// Update patient status
  /// Note: 'status' column does not exist, so this is a no-op.
  static Future<Patient> updatePatientStatus(
    String patientId,
    PatientStatus status,
  ) async {
    try {
      log.info('Updating patient status: $patientId -> $status (No-op)');

      // Return current patient state since we can't update status
      return await getPatient(patientId) ??
          Patient(
            id: patientId,
            createdAt: DateTime.now(),
            fullName: 'Unknown',
            status: status,
            doctorId: '',
          );

      /*
      final updates = {
        'status': status.value,
        if (status == PatientStatus.completed)
          'last_visit': DateTime.now().toIso8601String(),
      };

      return await updatePatient(patientId, updates);
      */
    } catch (e) {
      log.severe('Failed to update patient status: $patientId', e);
      rethrow;
    }
  }

  /// Mark patient as inactive (soft delete)
  /// Note: 'is_active' column does not exist, so this is a no-op.
  static Future<void> deactivatePatient(String patientId) async {
    try {
      log.info('Deactivating patient: $patientId (No-op)');

      /*
      await supabase
          .from('patients')
          .update({'is_active': false})
          .eq('id', patientId);
      */

      log.info('Deactivated patient: $patientId');
    } catch (e) {
      log.severe('Failed to deactivate patient: $patientId', e);
      rethrow;
    }
  }

  /// Permanently delete patient and cascade to related data
  static Future<void> deletePatient(String patientId) async {
    try {
      log.info('Deleting patient: $patientId');

      // 1. Delete from database (Postgres should handle cascade if configured, but we do it explicitly for safety)
      // Note: Assuming RLS policies allow deletion
      await supabase.from('patients').delete().eq('id', patientId);

      // 2. Delete from Storage (Cascade delete for files)
      // We need to list and delete all files in the patient's folder
      try {
        final storage = supabase.storage.from('medical_notes');
        final files = await storage.list(path: patientId);

        if (files.isNotEmpty) {
          final filePaths = files.map((f) => '$patientId/${f.name}').toList();
          await storage.remove(filePaths);
        }

        // Also try to delete subfolders if any (Storage doesn't support recursive delete easily,
        // but we can try to delete known structure if needed. For now, we assume flat or simple structure)
      } catch (storageError) {
        log.warning(
          'Failed to clean up storage for patient: $patientId',
          storageError,
        );
        // Continue even if storage cleanup fails, as DB record is gone
      }

      log.info('Deleted patient: $patientId');
    } catch (e) {
      log.severe('Failed to delete patient: $patientId', e);
      rethrow;
    }
  }

  /// Watch for real-time changes to patients
  static Stream<List<Patient>> watchPatients() {
    return supabase
        .from('patients')
        .stream(primaryKey: ['id'])
        .order('created_at', ascending: false)
        .map(
          (data) => data
              .map((json) => Patient.fromJson(json as Map<String, dynamic>))
              .toList(),
        );
  }

  /// Watch for real-time changes to waiting queue
  /// Note: 'status' column does not exist, so this watches all patients.
  static Stream<List<Patient>> watchWaitingQueue() {
    return supabase
        .from('patients')
        .stream(primaryKey: ['id'])
        // .eq('status', 'waiting') // Column does not exist
        .order('created_at', ascending: true)
        .map(
          (data) => data
              .map((json) => Patient.fromJson(json as Map<String, dynamic>))
              .toList(),
        );
  }
}
