import 'package:intl/intl.dart';

class ReportFormatter {
  static String formatToMarkdown({
    required Map<String, dynamic> reportData,
    required String? patientId,
    required String? patientName,
    required String? registrationNumber,
  }) {
    final sb = StringBuffer();

    // 1. Title
    sb.writeln('# 🏥 Clinical Assessment Report');
    sb.writeln();

    // 2. Metadata (Patient Info & Date)
    final now = DateTime.now();
    final dateStr = DateFormat('dd MMM yyyy, h:mm a').format(now);

    sb.writeln('**Patient Name:** ${patientName ?? 'Unknown'}');
    if (registrationNumber != null) {
      sb.writeln('**ID:** $registrationNumber');
    }
    sb.writeln('**Date:** $dateStr');
    sb.writeln();
    sb.writeln('---');
    sb.writeln();

    // 3. Sections

    // Current Symptoms
    sb.writeln('### 📝 Present Complaints & History');
    sb.writeln(reportData['current_symptoms'] ?? '*Not mentioned*');
    sb.writeln();

    // Premorbid Personality
    if (reportData['premorbid_personality'] != null &&
        reportData['premorbid_personality'] != 'Not mentioned') {
      sb.writeln('### 👤 Premorbid Personality');
      sb.writeln(reportData['premorbid_personality']);
      sb.writeln();
    }

    // Past History
    if (reportData['past_history'] != null &&
        reportData['past_history'] != 'Not mentioned') {
      sb.writeln('### 🕰️ Past History');
      sb.writeln(reportData['past_history']);
      sb.writeln();
    }

    // Family History
    if (reportData['family_history'] != null &&
        reportData['family_history'] != 'Not mentioned') {
      sb.writeln('### 👪 Family History');
      sb.writeln(reportData['family_history']);
      sb.writeln();
    }

    // MSE
    sb.writeln('### 🧠 Mental Status Examination');
    final mse = reportData['mental_status_examination'];
    if (mse is Map) {
      mse.forEach((key, value) {
        final formattedKey = key.toString().replaceAll('_', ' ').toUpperCase();
        sb.writeln('- **$formattedKey:** $value');
      });
    } else if (mse is String) {
      sb.writeln(mse);
    } else {
      sb.writeln('*Not mentioned*');
    }
    sb.writeln();

    // Diagnosis
    sb.writeln('### 🏁 Diagnosis');
    sb.writeln('**${reportData['provided_diagnosis'] ?? 'Not mentioned'}**');
    sb.writeln();

    sb.writeln('---');
    sb.writeln();

    // Medications
    sb.writeln('### 💊 Prescribed Medications');
    final meds = reportData['medications'] as List?;
    if (meds != null && meds.isNotEmpty) {
      sb.writeln('| Medication | Frequency | Duration | Remarks |');
      sb.writeln('| :--- | :--- | :--- | :--- |');
      for (final m in meds) {
        if (m is Map) {
          final name = m['name'] ?? 'N/A';
          final freq = m['frequency'] ?? 'N/A';
          final duration = m['duration'] ?? 'N/A';
          final remarks = m['remarks'] ?? '';
          sb.writeln('| **$name** | $freq | $duration | $remarks |');
        }
      }
    } else {
      sb.writeln('*None prescribed or not mentioned.*');
    }
    sb.writeln();
    sb.writeln('---');
    sb.writeln();
    sb.write(
      '> *This report was automatically generated by Synapse AI based on clinical notes.*',
    );

    return sb.toString();
  }
}
